server:
  port: 8989

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: operator-service
          uri: lb://OPERATOR-SERVICE
          predicates:
            - Path=/operators/**

        - id: recharge-service
          uri: lb://RECHARGE-SERVICE
          predicates:
            - Path=/recharges/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost