server.port=8087
spring.security.user.name=ram
spring.security.user.password=ram123



# user name is  : user (on browser)
# Spring Framework generated password  
#spring-security-user.name=ram
#spring-security-user.password=ram123