server:
  port: 9080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka