server:
  port: 9090

resilience4j:
  circuitbreaker:
    instances:
      productService:
        minimum-number-of-calls: 1
        failure-rate-threshold: 50
        sliding-window-size: 5
        wait-duration-in-open-state: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers